return {
	start=function()
		game.states.current = game.stateNames.startGame
		game.player={
			lives=3,
			level=1,
			score=0,
			levelCounter=0,
			speed=10,
			tail=5,
			bonuses={
				ouya={
					o=false,
					u=false,
					y=false,
					a=false,
					ouyaCount=0,
					oCount=0,
					uCount=0,
					yCount=0,
					aCount=0
				},
				jetlag={
					count=0,
					j=false,
					e=false,
					t=false,
					l=false,
					a=false,
					g=false
				}
			}
		}
		game.states.startGame.finish(game.stateNames.startRun)
	end,
	finish=function(nextState)
		game.states[nextState].start()
	end,
	onKeyDown=function(theKey)
	end,
	onKeyUp=function(theKey)
	end
}
